In [4]:
import numpy as np

points = np.array([
    [1.5, 2.3, 255, 0, 0], 
    [3.0, 4.1, 0, 255, 0],
])
for point in points:
    print(f"({point[0]}, {point[1]}),  ({point[2]}, {point[3]}, {point[4]})")


(1.5, 2.3),  (255.0, 0.0, 0.0)
(3.0, 4.1),  (0.0, 255.0, 0.0)


In [ ]:
import numpy as np

float_array = np.array([1.5, -2.3, 3.14, 0.0], dtype=np.float32)

float_array = float_array.astype(np.int32)  

print(float_array)


[ 1 -2  3  0]


In [11]:
import numpy as np

data = np.genfromtxt("16.csv", delimiter=",", dtype=np.float32)

print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [12]:
import numpy as np

arr = np.array([[10, 20], [30, 40]])

for index, value in np.ndenumerate(arr):
    print(f"Indeks: {index}, Qiymat: {value}")



Indeks: (0, 0), Qiymat: 10
Indeks: (0, 1), Qiymat: 20
Indeks: (1, 0), Qiymat: 30
Indeks: (1, 1), Qiymat: 40


In [1]:
import numpy as np

dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]
arr = np.array([((1.0, 2.0), (255, 0, 0)), ((3.0, 4.0), (0, 255, 0))], dtype=dtype)
print(arr)


[((1., 2.), (255,   0, 0)) ((3., 4.), (  0, 255, 0))]


In [1]:
from scipy.spatial import distance

points = np.random.rand(100, 2)
distances = distance.cdist(points, points)
print(distances)


NameError: name 'np' is not defined

In [3]:
arr = np.arange(10, dtype=np.float32)
arr = arr.view(np.int32)
print(arr)


[         0 1065353216 1073741824 1077936128 1082130432 1084227584
 1086324736 1088421888 1090519040 1091567616]


In [4]:
from io import StringIO

text = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

data = np.genfromtxt(StringIO(text), delimiter=",", filling_values=0)
print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  0.  7.  8.]
 [ 0.  0.  9. 10. 11.]]


In [5]:
arr = np.array([10, 20, 30])
for i, val in np.ndenumerate(arr):
    print(i, val)


(0,) 10
(1,) 20
(2,) 30


In [6]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
gaussian = np.exp(-(x**2 + y**2))
print(gaussian)


[[0.13533528 0.20090196 0.27018673 0.32919299 0.36336564 0.36336564
  0.32919299 0.27018673 0.20090196 0.13533528]
 [0.20090196 0.2982341  0.40108566 0.48867903 0.53940751 0.53940751
  0.48867903 0.40108566 0.2982341  0.20090196]
 [0.27018673 0.40108566 0.53940751 0.65720907 0.72543221 0.72543221
  0.65720907 0.53940751 0.40108566 0.27018673]
 [0.32919299 0.48867903 0.65720907 0.8007374  0.88385983 0.88385983
  0.8007374  0.65720907 0.48867903 0.32919299]
 [0.36336564 0.53940751 0.72543221 0.88385983 0.97561098 0.97561098
  0.88385983 0.72543221 0.53940751 0.36336564]
 [0.36336564 0.53940751 0.72543221 0.88385983 0.97561098 0.97561098
  0.88385983 0.72543221 0.53940751 0.36336564]
 [0.32919299 0.48867903 0.65720907 0.8007374  0.88385983 0.88385983
  0.8007374  0.65720907 0.48867903 0.32919299]
 [0.27018673 0.40108566 0.53940751 0.65720907 0.72543221 0.72543221
  0.65720907 0.53940751 0.40108566 0.27018673]
 [0.20090196 0.2982341  0.40108566 0.48867903 0.53940751 0.53940751
  0.48867903

In [7]:
arr = np.random.rand(5, 5)
arr -= arr.mean(axis=1, keepdims=True)
print(arr)


[[-0.16310376 -0.03112971 -0.21253932  0.10568625  0.30108654]
 [-0.0956198   0.24936553 -0.49618999  0.27956274  0.06288152]
 [-0.12941026  0.26623992 -0.24060296  0.04262251  0.06115078]
 [-0.37257423 -0.20021767  0.4094243  -0.09581957  0.25918717]
 [-0.47306015  0.2644336  -0.28668878  0.04256871  0.45274662]]


In [8]:
arr = np.random.randint(0, 100, (5, 5))
sorted_arr = arr[arr[:, 2].argsort()]
print(sorted_arr)


[[42 57 14 97 59]
 [62 89 18 37 81]
 [47 93 19 63 74]
 [16 97 47 49 22]
 [70 89 67 35 98]]


In [9]:
arr = np.array([[1, 0, 3], [4, 0, 6], [7, 0, 9]])
print(np.all(arr == 0, axis=0))


[False  True False]


In [10]:
arr = np.array([1, 3, 7, 10, 15])
val = 8
nearest = arr[np.abs(arr - val).argmin()]
print(nearest)


7


In [11]:
A = np.ones((1,3))
B = np.ones((3,1))
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [13]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="array"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

arr = NamedArray([1,2,3], name="MyArray")
print(arr.name)


MyArray


In [14]:
arr = np.zeros(10)
idx = np.array([2, 2, 3, 4, 4])
np.add.at(arr, idx, 1)
print(arr)


[0. 0. 2. 1. 2. 0. 0. 0. 0. 0.]


In [15]:
X = np.array([1, 2, 3, 4])
I = np.array([0, 1, 0, 1])
F = np.zeros(2)
np.add.at(F, I, X)
print(F)


[4. 6.]
